# Notebook de traducción de R a Python

## Libraries

```{r}
Código en R

rm(list = ls())
setwd("/home/a/Escritorio/TFM/datos")
library(data.table)
require(Seurat)
library("anndata")
library(SeuratDisk)
library(zellkonverter)
#https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html

In [1]:
import pandas as pd
from anndata import read_h5ad

## Data

```{r}
Código en R

#Convert("local.h5ad", dest ="h5seurat",overwrite=TRUE)
#datos <- LoadH5Seurat("local.h5seurat",meta.data = FALSE, misc = FALSE)
#Error: Missing required datasets 'levels' and 'values'

datos <- readH5AD("local.h5ad")
datos <- as.Seurat(datos, counts = "X", data = NULL)

#datos <- CreateSeuratObject(counts = t(ad$X), meta.data = ad$obs)
#datos <- read_h5ad("local.h5ad")
#datos <- CreateSeuratObject(counts = t(datos$X), meta.data = datos$obs)
#data <- read_h5ad("local.h5ad")
#data <- CreateSeuratObject(counts = data$X, meta.data = data$obs)
#print(str(data))
#pbmcLarge <- NormalizeData(pbmcLarge)

tipos <- as.data.frame(table(datos@meta.data$cell_type), row.names = "Var1")
tipos["ConWay20"] <- as.data.frame(table(datos[,datos@meta.data$Origin == "Conway20"]@meta.data$cell_type), row.names = "Var1")
tipos["Dumas20"] <- as.data.frame(table(datos[,datos@meta.data$Origin == "Dumas20"]@meta.data$cell_type), row.names = "Var1")
tipos["Hinze20"] <- as.data.frame(table(datos[,datos@meta.data$Origin == "Hinze20"]@meta.data$cell_type), row.names = "Var1")
tipos["Janosevic21"] <- as.data.frame(table(datos[,datos@meta.data$Origin == "Janosevic21"]@meta.data$cell_type), row.names = "Var1")
tipos["Kirita20"] <- as.data.frame(table(datos[,datos@meta.data$Origin == "Kirita20"]@meta.data$cell_type), row.names = "Var1")
tipos["Miao21"] <- as.data.frame(table(datos[,datos@meta.data$Origin == "Miao21"]@meta.data$cell_type), row.names = "Var1")
tipos["Park18"] <- as.data.frame(table(datos[,datos@meta.data$Origin == "Park18"]@meta.data$cell_type), row.names = "Var1")
tipos["Wu19"] <- as.data.frame(table(datos[,datos@meta.data$Origin == "Wu19"]@meta.data$cell_type), row.names = "Var1")

fwrite(x = tipos, row.names = TRUE,file = "tipos.csv")

#dataAll <- as.data.frame(as.matrix(datos@assays$originalexp@data))
#metadataAll <- as.data.frame(datos@meta.data)
#fwrite(x = dataAll, row.names = TRUE,file = "dataAll.csv")
#fwrite(x = metadataAll, row.names = TRUE,file = "metadatosAll.csv")

In [3]:
# Cambiar el directorio de trabajo
#os.chdir("/home/a/Escritorio/TFM/datos")

# Leer el archivo h5ad
datos = read_h5ad("/home/a/Escritorio/TFM/src/NSForest/data/local.h5ad")

# Crear un dataframe con el recuento de tipos celulares en datos
tipos = pd.DataFrame(datos.obs['cell_type'].value_counts())
tipos.columns = ['All']

# Filtrar y contar los tipos celulares para cada origen específico
for origen in ["Conway20", "Dumas20", "Hinze20", "Janosevic21", "Kirita20", "Miao21", "Park18", "Wu19"]:
    tipos[origen] = datos[datos.obs['Origin'] == origen].obs['cell_type'].value_counts()

# Escribir el dataframe en un archivo CSV
tipos.to_csv("tipos.csv", index=True)

In [5]:
tipos

,All,Conway20,Dumas20,Hinze20,Janosevic21,Kirita20,Miao21,Park18,Wu19
cell_type,,,,,,,,,
epithelial cell of proximal tubule,72832,4563.0,NaN,19247.0,5944.0,10578.0,12832.0,13152.0,6516.0
kidney distal convoluted tubule epithelial cell,16381,129.0,NaN,1988.0,963.0,1449.0,6336.0,4890.0,626.0
endothelial cell,11702,155.0,6240.0,781.0,531.0,2839.0,186.0,638.0,332.0
kidney collecting duct principal cell,4975,75.0,NaN,1939.0,158.0,1613.0,545.0,369.0,276.0
kidney connecting tubule epithelial cell,3903,27.0,NaN,1034.0,206.0,991.0,273.0,831.0,541.0
kidney loop of Henle medullary thick ascending limb epithelial cell,3840,65.0,NaN,1186.0,122.0,1951.0,67.0,446.0,3.0
native cell,3649,163.0,NaN,1126.0,167.0,2.0,548.0,1385.0,258.0
kidney loop of Henle cortical thick ascending limb epithelial cell,3600,283.0,NaN,796.0,111.0,2019.0,76.0,310.0,5.0
glomerular endothelial cell,3547,138.0,3017.0,81.0,3.0,3.0,22.0,283.0,NaN
kidney loop of Henle epithelial cell,3484,47.0,NaN,434.0,377.0,1421.0,405.0,793.0,7.0
renal beta-intercalated cell,2447,37.0,NaN,522.0,93.0,411.0,429.0,691.0,264.0
T cell,1721,32.0,NaN,23.0,226.0,105.0,502.0,833.0,NaN
kidney loop of Henle thin ascending limb epithelial cell,1610,7.0,NaN,265.0,20.0,1.0,30.0,26.0,1261.0
renal alpha-intercalated cell,1488,18.0,NaN,291.0,44.0,486.0,212.0,237.0,200.0
macrophage,1294,70.0,NaN,106.0,4.0,451.0,189.0,358.0,116.0
fibroblast,1070,5.0,NaN,220.0,1.0,826.0,NaN,8.0,10.0
kidney cortex tubule cell,810,5.0,NaN,281.0,4.0,394.0,60.0,60.0,6.0
podocyte,558,NaN,NaN,168.0,NaN,121.0,57.0,13.0,199.0
dendritic cell,537,4.0,421.0,16.0,96.0,NaN,NaN,NaN,NaN
kidney loop of Henle thin descending limb epithelial cell,372,3.0,NaN,NaN,NaN,NaN,NaN,85.0,284.0
mesangial cell,316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,316.0
kidney efferent arteriole endothelial cell,242,NaN,241.0,NaN,1.0,NaN,NaN,NaN,NaN
natural killer cell,201,2.0,NaN,NaN,10.0,NaN,4.0,185.0,NaN
B cell,175,11.0,NaN,NaN,12.0,NaN,1.0,151.0,NaN
vasa recta descending limb cell,167,8.0,152.0,1.0,6.0,NaN,NaN,NaN,NaN
pericyte,154,3.0,NaN,36.0,37.0,75.0,NaN,2.0,1.0
kidney glomerular epithelial cell,117,1.0,NaN,38.0,3.0,75.0,NaN,NaN,NaN
neutrophil,68,NaN,NaN,NaN,3.0,NaN,37.0,28.0,NaN
kidney collecting duct epithelial cell,59,1.0,NaN,NaN,2.0,NaN,2.0,54.0,NaN
macula densa epithelial cell,46,NaN,NaN,7.0,NaN,39.0,NaN,NaN,NaN
kidney afferent arteriole endothelial cell,36,NaN,35.0,NaN,1.0,NaN,NaN,NaN,NaN

```{r}

Codigo en R

dataConway20 <- as.data.frame(as.matrix(datosClaudio@assays$originalexp@data[,datosClaudio@meta.data$Origin == "Conway20"]))
fwrite(x = dataConway20, row.names = TRUE,file = "dataConway20.csv")
metadataConway20 <- as.data.frame(datosClaudio@meta.data[datosClaudio@meta.data$Origin == "Conway20",])
fwrite(x = metadataConway20, row.names = TRUE,file = "metadatosConway20.csv")

dataDumas20 <- as.data.frame(as.matrix(datosClaudio@assays$originalexp@data[,datosClaudio@meta.data$Origin == "Dumas20"]))
fwrite(x = dataDumas20, row.names = TRUE,file = "dataDumas20.csv")
metadataDumas20 <- as.data.frame(datosClaudio@meta.data[datosClaudio@meta.data$Origin == "Dumas20",])
fwrite(x = metadataDumas20, row.names = TRUE,file = "metadatosDumas20.csv")

dataHinze20 <- as.data.frame(as.matrix(datosClaudio@assays$originalexp@data[,datosClaudio@meta.data$Origin == "Hinze20"]))
fwrite(x = dataHinze20, row.names = TRUE,file = "dataHinze20.csv")
metadataHinze20 <- as.data.frame(datosClaudio@meta.data[datosClaudio@meta.data$Origin == "Hinze20",])
fwrite(x = metadataHinze20, row.names = TRUE,file = "metadatosHinze20.csv")

dataJanosevic21 <- as.data.frame(as.matrix(datosClaudio@assays$originalexp@data[,datosClaudio@meta.data$Origin == "Janosevic21"]))
fwrite(x = dataJanosevic21, row.names = TRUE,file = "dataJanosevic21.csv")
metadataJanosevic21 <- as.data.frame(datosClaudio@meta.data[datosClaudio@meta.data$Origin == "Janosevic21",])
fwrite(x = metadataJanosevic21, row.names = TRUE,file = "metadatosJanosevic21.csv")

dataKirita20 <- as.data.frame(as.matrix(datosClaudio@assays$originalexp@data[,datosClaudio@meta.data$Origin == "Kirita20"]))
fwrite(x = dataKirita20, row.names = TRUE,file = "dataKirita20.csv")
metadataKirita20 <- as.data.frame(datosClaudio@meta.data[datosClaudio@meta.data$Origin == "Kirita20",])
fwrite(x = metadataKirita20, row.names = TRUE,file = "metadatosKirita20.csv")

dataMiao21 <- as.data.frame(as.matrix(datosClaudio@assays$originalexp@data[,datosClaudio@meta.data$Origin == "Miao21"]))
fwrite(x = dataMiao21, row.names = TRUE,file = "dataMiao21.csv")
metadataMiao21 <- as.data.frame(datosClaudio@meta.data[datosClaudio@meta.data$Origin == "Miao21",])
fwrite(x = metadataMiao21, row.names = TRUE,file = "metadatosMiao21.csv")

dataPark18 <- as.data.frame(as.matrix(datosClaudio@assays$originalexp@data[,datosClaudio@meta.data$Origin == "Park18"]))
fwrite(x = dataPark18, row.names = TRUE,file = "dataPark18.csv")
metadataPark18 <- as.data.frame(datosClaudio@meta.data[datosClaudio@meta.data$Origin == "Park18",])
fwrite(x = metadataPark18, row.names = TRUE,file = "metadatosPark18.csv")

dataWu19 <- as.data.frame(as.matrix(datosClaudio@assays$originalexp@data[,datosClaudio@meta.data$Origin == "Wu19"]))
fwrite(x = dataWu19, row.names = TRUE,file = "dataWu19.csv")
metadataWu19 <- as.data.frame(datosClaudio@meta.data[datosClaudio@meta.data$Origin == "Wu19",])
fwrite(x = metadataWu19, row.names = TRUE,file = "metadatosWu19.csv")

In [6]:
# Leer el archivo h5ad
datos = read_h5ad("local.h5ad")

# Filtrar y escribir los datos y metadatos para cada origen específico
for origen in ["Conway20", "Dumas20", "Hinze20", "Janosevic21", "Kirita20", "Miao21", "Park18", "Wu19"]:
    # Filtrar los datos y metadatos para el origen actual
    data = datos[datos.obs['Origin'] == origen].X
    metadata = datos.obs[datos.obs['Origin'] == origen]
    
    # Convertir los datos y metadatos en dataframes
    data_df = pd.DataFrame(data, index=metadata.index)
    metadata_df = pd.DataFrame(metadata)
    
    # Escribir los dataframes en archivos CSV
    data_df.to_csv(f"data{origen}.csv", index=True, header=False)
    metadata_df.to_csv(f"metadatos{origen}.csv", index=True)

```{r}
Código en R

rm(list = ls())
setwd("/Users/luisjavierherrera/session-differentialexpression")
require(Seurat)
library(SeuratDisk)
library(data.table)
library("scatterplot3d") # load

data <- data.frame(fread("dataHinze20.csv"), row.names=1)
dataT <- transpose(data)
rownames(dataT) <- colnames(data)
colnames(dataT) <- rownames(data)
data <- dataT
rm(dataT)
data <- data[,!(colSums(data) == 0)]

metadata <- data.frame(fread("metadatosHinze20.csv"), row.names=1)
metadata$cell_type <- as.factor(metadata$cell_type)
nClasses <- nlevels(metadata$cell_type)
#index <- (metadata$celltype == "CD4 T cell") | (metadataL$celltype == "CD8 T cell") 
#dataN <- data[index,]
#data <- dataN
#label <- droplevels(metadata$celltype[index])
labels <- as.factor(metadata$cell_type)
```

In [7]:
# Limpiar el espacio de trabajo
# No es necesario en Python, ya que las variables se sobrescriben al reasignarlas
# Se omite rm(list = ls())

# Establecer el directorio de trabajo
# En Python, esto no es necesario para cargar archivos desde el sistema de archivos local
# Se omite setwd("/Users/luisjavierherrera/session-differentialexpression")

# Importar las librerías necesarias

# Cargar los datos desde archivos CSV
data = pd.read_csv("dataHinze20.csv", index_col=0)
metadata = pd.read_csv("metadatosHinze20.csv", index_col=0)

# Transponer los datos
data = data.transpose()

# Eliminar las columnas con todas las entradas cero
data = data.loc[:, (data != 0).any(axis=0)]

# Convertir la columna 'cell_type' a tipo de dato categórico
metadata['cell_type'] = metadata['cell_type'].astype('category')

# Obtener el número de clases únicas en la columna 'cell_type'
nClasses = len(metadata['cell_type'].cat.categories)

# Crear el factor de las etiquetas 'cell_type'
labels = metadata['cell_type']

In [8]:
labels

barcode
AAACCTGAGAGCTGCA-4-0                 epithelial cell of proximal tubule
AAACCTGAGAGCTTCT-4-0    kidney distal convoluted tubule epithelial cell
AAACCTGAGCCCTAAT-4-0                 epithelial cell of proximal tubule
AAACCTGAGGATGGAA-4-0                 epithelial cell of proximal tubule
AAACCTGAGGGTCTCC-4-0                 epithelial cell of proximal tubule
                                             ...
GCAGGAATACAT-5-0                     epithelial cell of proximal tubule
TACAAGACAAGG-5-0                     epithelial cell of proximal tubule
CATGCTCTTGGC-5-0                           renal beta-intercalated cell
AGGCATAAATAC-5-0                     epithelial cell of proximal tubule
TCCTACGCTTGT-5-0                     epithelial cell of proximal tubule
Name: cell_type, Length: 30586, dtype: category
Categories (23, object): ['T cell', 'dendritic cell', 'endothelial cell', 'epithelial cell of proximal tubule', ..., 'podocyte', 'renal alpha-intercalated cell', 'renal beta-intercalated cell', 'vasa recta descending limb cell']

In [9]:
nClasses

23

In [12]:
metadata

,Origin,suspension_type,n_genes,n_genes_by_counts,log1p_n_genes_by_counts,total_counts,log1p_total_counts,total_counts_mt,log1p_total_counts_mt,pct_counts_mt,...,assay_ontology_term_id,donor_id,cell_type,assay,disease,organism,sex,tissue,self_reported_ethnicity,development_stage
barcode,,,,,,,,,,,,,,,,,,,,,
AAACCTGAGAGCTGCA-4-0,Hinze20,nucleus,777,758,6.632002,1069.0,6.975414,7.0,2.079442,0.654818,...,EFO:0009899,pooled,epithelial cell of proximal tubule,10x 3' v2,normal,Mus musculus,male,kidney,na,early adult stage
AAACCTGAGAGCTTCT-4-0,Hinze20,nucleus,509,500,6.216606,654.0,6.484635,15.0,2.772589,2.293578,...,EFO:0009899,pooled,kidney distal convoluted tubule epithelial cell,10x 3' v2,normal,Mus musculus,male,kidney,na,early adult stage
AAACCTGAGCCCTAAT-4-0,Hinze20,nucleus,529,515,6.246107,723.0,6.584791,2.0,1.098612,0.276625,...,EFO:0009899,pooled,epithelial cell of proximal tubule,10x 3' v2,normal,Mus musculus,male,kidney,na,early adult stage
AAACCTGAGGATGGAA-4-0,Hinze20,nucleus,556,538,6.289716,710.0,6.566672,3.0,1.386294,0.422535,...,EFO:0009899,pooled,epithelial cell of proximal tubule,10x 3' v2,normal,Mus musculus,male,kidney,na,early adult stage
AAACCTGAGGGTCTCC-4-0,Hinze20,nucleus,561,547,6.306275,760.0,6.634633,2.0,1.098612,0.263158,...,EFO:0009899,pooled,epithelial cell of proximal tubule,10x 3' v2,normal,Mus musculus,male,kidney,na,early adult stage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GCAGGAATACAT-5-0,Hinze20,cell,456,451,6.113682,1099.0,7.003066,373.0,5.924256,33.939945,...,EFO:0008722,pooled,epithelial cell of proximal tubule,Drop-seq,normal,Mus musculus,male,kidney,na,early adult stage
TACAAGACAAGG-5-0,Hinze20,cell,204,201,5.308268,506.0,6.228511,231.0,5.446737,45.652176,...,EFO:0008722,pooled,epithelial cell of proximal tubule,Drop-seq,normal,Mus musculus,male,cortex of kidney,na,early adult stage
CATGCTCTTGGC-5-0,Hinze20,cell,363,354,5.872118,979.0,6.887553,459.0,6.131227,46.884575,...,EFO:0008722,pooled,renal beta-intercalated cell,Drop-seq,normal,Mus musculus,male,cortex of kidney,na,early adult stage
AGGCATAAATAC-5-0,Hinze20,cell,699,684,6.529419,1684.0,7.429521,523.0,6.261492,31.057007,...,EFO:0008722,pooled,epithelial cell of proximal tubule,Drop-seq,normal,Mus musculus,male,cortex of kidney,na,early adult stage
TCCTACGCTTGT-5-0,Hinze20,cell,431,424,6.052089,1065.0,6.971669,476.0,6.167517,44.694836,...,EFO:0008722,pooled,epithelial cell of proximal tubule,Drop-seq,normal,Mus musculus,male,outer medulla of kidney,na,early adult stage

In [13]:
metadata['cell_type']

barcode
AAACCTGAGAGCTGCA-4-0                 epithelial cell of proximal tubule
AAACCTGAGAGCTTCT-4-0    kidney distal convoluted tubule epithelial cell
AAACCTGAGCCCTAAT-4-0                 epithelial cell of proximal tubule
AAACCTGAGGATGGAA-4-0                 epithelial cell of proximal tubule
AAACCTGAGGGTCTCC-4-0                 epithelial cell of proximal tubule
                                             ...
GCAGGAATACAT-5-0                     epithelial cell of proximal tubule
TACAAGACAAGG-5-0                     epithelial cell of proximal tubule
CATGCTCTTGGC-5-0                           renal beta-intercalated cell
AGGCATAAATAC-5-0                     epithelial cell of proximal tubule
TCCTACGCTTGT-5-0                     epithelial cell of proximal tubule
Name: cell_type, Length: 30586, dtype: category
Categories (23, object): ['T cell', 'dendritic cell', 'endothelial cell', 'epithelial cell of proximal tubule', ..., 'podocyte', 'renal alpha-intercalated cell', 'renal beta-intercalated cell', 'vasa recta descending limb cell']